### ISSUE TITLE
no webpage at localhost:5000 , how to troubleshoot ?

### ISSUE THREAD

**Issue by AndKe** [SamuelDudley/MAVCesium#4]
I did install as expected using git clone , and submodules.
I see no errors, but nor do I see anything at port 5000.. :(

**Comment by AndKe** [comment]
apparently it works once mavlink data is received, not before..

**Comment by SamuelDudley** [comment]
Hi,
Glad it worked for you.
I'll make an issue for this, as it would be nice to have the system give some feedback prior to mavlink data.

Let me know if you run into other issues and ill do my best to help out.
Thanks,
Sam

**Comment by AndKe** [comment]
Hi, thank you for the software, I am happy to see you are still working on it.  (was unsure due to long time since last commit)
Until the server starts before mavlink data, consider updating the readme.md with  information about it, following the readme I expected to see something at port 5000 and assumed something failed.

**Comment by SamuelDudley** [comment]
Updated the readme so that the user knows valid mavlink msg's are required prior to visualisation ee6584d496a67ebe4c5d532d1d17c9ba05e3ff37

**Comment by SamuelDudley** [comment]
Added a waiting for data message #9

**Comment by AndKe** [comment]
on load, it would be nice if a message with the URL popped up in mavproxy console, it could be clickable, but would always he helpful to those who have not used cesium a lot yet.

**Comment by SamuelDudley** [comment]
Thanks, that's a great idea! I'll see what I can do about the clickable link, but a text output will be quite simple.

**Comment by AndKe** [comment]
Text output should be enough,  additionally, you could ask system to open
the URL, so it would start in  browser  right away.

On 20 Feb 2017 10:06 a.m., "Samuel Dudley" <notifications@github.com> wrote:

Thanks, that's a great idea! I'll see what I can do about the clickable
link, but a text output will be quite simple.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/SamuelDudley/MAVCesium/issues/4#issuecomment-281023797>,
or mute the thread

**Comment by AndKe** [comment]
... basically
https://www.google.no/amp/s/pythonconquerstheuniverse.wordpress.com/2010/10/16/how-to-open-a-web-browser-from-python/amp/

**Comment by SamuelDudley** [comment]
Hi,
Thanks for the links. For the moment I have the module printing a message in the MAVProxy console and auto loading a tab. If the MAVProxy [PR](https://github.com/ArduPilot/MAVProxy/pull/381) is accepted I will remove the auto load feature from MAVCesium and the user can easily double click the link from the MAVProxy console window.

**Comment by SamuelDudley** [comment]
Thanks again for the input. I'll have a look at implementing some of the trickier HUD / UI bits after I have the configuration control worked out... Feel free to keep adding ideas / requests to the enhancements issue.
Cheers,
Sam

**Comment by SamuelDudley** [comment]
https://github.com/ArduPilot/MAVProxy/pull/381 was merged today adding support for click-able URLs in the MAVProxy console.
